{
  TBA = {
    name = 'The Blood Angels',
    rcl_rank = 16,
    combined_power_rank = 15,
    members = [ 'Builder', 'Dubulicious', 'duckymirror', 'kotyara' ],
    slack_channel = null,
    abbreviation = 'TBA',
    alliance_power_rank = 13,
    combined_gcl_rank = 16,
    logo = '5eed407ca931d58.png',
    color = '#000000',
    spawns_rank = 16,
    members_rank = 11,
    alliance_gcl_rank = 18
  },
  culture = {
    name = 'The Culture',
    rcl_rank = 5,
    combined_power_rank = 6,
    members = [
      'ags131',       'anisoptera',
      'AWRyder',      'basepi',
      'Bombedoblib',  'Bovius',
      'cyberblast',   'daboross',
      'DarkTrooper7', 'Dissi',
      'dormando',     'Esryok',
      'evilmaniac',   'Heilos',
      'Hernanduer',   'maka_RTH',
      'n00bish',      'NhanHo',
      'Prime',        'SamTheCat',
      'Silesia',      'Skorp',
      'stybbe',       'tedivm',
      'tinnvec',      'Waveofbabies',
      'Zergling'
    ],
    slack_channel = 'theculture_public',
    abbreviation = 'culture',
    alliance_power_rank = 6,
    combined_gcl_rank = 5,
    logo = '87372e6c80dc05f.png',
    color = '#000000',
    spawns_rank = 6,
    members_rank = 6,
    alliance_gcl_rank = 6
  },
  VIP = {
    name = 'Vicesimal Independence Pact',
    rcl_rank = 10,
    combined_power_rank = 9,
    members = [
      'dund',
      'Faff',
      'Haxxeris',
      'ManVsRice',
      'MonsieurLee',
      'Mwaahahahaha',
      'Tempest',
      'Unstable'
    ],
    slack_channel = 'vip',
    abbreviation = 'VIP',
    alliance_power_rank = 9,
    combined_gcl_rank = 11,
    logo = '6de8bcdb1be8b78.png',
    color = '#000000',
    spawns_rank = 10,
    members_rank = 9,
    alliance_gcl_rank = 12
  },
  YP = {
    name = 'Ypsilon Pact',
    rcl_rank = 1,
    combined_power_rank = 1,
    members = [
      'adammada',    'admon',      'Alcardian',
      'Baj',         'cazantyl',   'DoctorPC',
      'Geir1983',    'Issacar',    'joethebarber',
      'Kenji',       'Komir',      'Laeros',
      'Lexxicon',    'likeafox',   'Lolzor',
      'mnuck',       'ncsupheo',   'NobodysNightmare',
      'omnomwombat', 'Orlet',      'Parthon',
      'Plemenit',    'poppahorse', 'Publiccert',
      'Regnare',     'Reizul',     'SimpleEnigma',
      'smitt33',     'Solace',     'Subodai',
      'Tantalas',    'Tijnoz',     'Totalschaden',
      'tron',        'TuN9aN0',    'Turves',
      'Vlahn',       'W4rl0ck',    'weaves',
      'wolffman122', 'Xaq',        'xndo',
      'xsinx',       'Yilmas',     'Zolcsika',
      'Zpike',       'Zyzyzyryxy'
    ],
    slack_channel = 'ypsilonpact-public',
    abbreviation = 'YP',
    alliance_power_rank = 3,
    combined_gcl_rank = 1,
    logo = '367765f8bd52ea7.png',
    color = '#000000',
    spawns_rank = 1,
    members_rank = 1,
    alliance_gcl_rank = 1
  },
  SCFR = {
    name = 'Screeps France',
    rcl_rank = 15,
    combined_power_rank = 21,
    members = [ 'Hollish', 'iKlem' ],
    slack_channel = 'screeps_francais',
    abbreviation = 'SCFR',
    alliance_power_rank = 21,
    combined_gcl_rank = 19,
    logo = '0a6ccfda05611bd.png',
    color = '#000000',
    spawns_rank = 15,
    members_rank = 17,
    alliance_gcl_rank = 19
  },
  nato = {
    name = 'NATO',
    rcl_rank = 13,
    combined_power_rank = 20,
    members = [
      'Amadox',
      '_BoB_',
      'MartyMoo',
      'maxbit89',
      'Midnight_Creeper',
      'Nev0x',
      'nnog',
      'sparr',
      'Triscus'
    ],
    slack_channel = 'nato',
    abbreviation = 'nato',
    alliance_power_rank = 20,
    combined_gcl_rank = 18,
    logo = '7914e5e9f5d1eb9.gif',
    color = null,
    spawns_rank = 13,
    members_rank = 16,
    alliance_gcl_rank = 17
  },
  TNG = {
    name = 'TNG',
    rcl_rank = 12,
    combined_power_rank = 16,
    members = [ 'Genovese', 'heggico', 'QzarSTB' ],
    slack_channel = null,
    abbreviation = 'TNG',
    alliance_power_rank = 16,
    combined_gcl_rank = 13,
    logo = null,
    color = '#7d7162',
    spawns_rank = 12,
    members_rank = 21,
    alliance_gcl_rank = 10
  },
  Hive = {
    name = 'The Hive',
    rcl_rank = 11,
    combined_power_rank = 10,
    members = [
      'Baldey',       'CrazyPilot',
      'Dewey',        'Dragnar',
      'gastraph',     'Greenfox',
      'haaduken',     'IFor',
      'kraiik',       'Lamus',
      'McGnomington', 'PervyPenguin',
      'QuickStrike',  'Rajecz',
      'rouhet',       'Tirao',
      'userwins',     'Vervust',
      'Violaman',     'Vultured'
    ],
    slack_channel = 'None',
    abbreviation = 'Hive',
    alliance_power_rank = 8,
    combined_gcl_rank = 9,
    logo = 'bb156849fe90019.jpg',
    color = '#000000',
    spawns_rank = 11,
    members_rank = 13,
    alliance_gcl_rank = 7
  },
  TGA = {
    name = 'Tremendous Group Advantage',
    rcl_rank = 21,
    combined_power_rank = 14,
    members = [ 'CeilingPanda', 'Fiskmans' ],
    slack_channel = null,
    abbreviation = 'TGA',
    alliance_power_rank = 14,
    combined_gcl_rank = 20,
    logo = null,
    color = '#000000',
    spawns_rank = 19,
    members_rank = 19,
    alliance_gcl_rank = 20
  },
  UoP = {
    name = 'The Union of Proletariats',
    rcl_rank = 8,
    combined_power_rank = 7,
    members = [
      'a02418',        'Asixa',            'Aurium',
      'ayoitsLuke',    'BBleae',           'BestJohn',
      'bestkurisu',    'BoosterKevin',     'Cciradih',
      'ChenyangDu',    'Christinayo',      'ciwomuli',
      'composite_x',   'Cookies',          'czc',
      'EricGuo',       'fangxm',           'foraphe',
      'foreyes1001',   'Hibari',           'HoPGoldy',
      'KevinH',        'Lampese',          'Lev_CT',
      'LisbethCeceri', 'LoAT_Kyoma',       'LokiSharp',
      'masterkeze',    'Noswir',           'RoyalKnight',
      'sjfhsjfh',      'Stranger130126',   'Torara',
      'TPEZ',          'Unwannadie',       'WheatEars',
      'wyt',           'Yuandiaodiaodiao', 'zzsstt644'
    ],
    slack_channel = 'uop',
    abbreviation = 'UoP',
    alliance_power_rank = 10,
    combined_gcl_rank = 7,
    logo = '84058846ec8e6f8.png',
    color = '#000000',
    spawns_rank = 8,
    members_rank = 2,
    alliance_gcl_rank = 11
  },
  COJ = {
    name = 'Caliphate of Jurbs',
    rcl_rank = 18,
    combined_power_rank = 12,
    members = [
      'Douggernort',
      'Lithia',
      'Radonite',
      'rysade',
      'SirFrump',
      'siro'
    ],
    slack_channel = 'None',
    abbreviation = 'COJ',
    alliance_power_rank = 11,
    combined_gcl_rank = 17,
    logo = 'e249cf1cb420778.png',
    color = '#000000',
    spawns_rank = 20,
    members_rank = 15,
    alliance_gcl_rank = 15
  },
  AYCE = {
    name = 'All You Can Eat',
    rcl_rank = 3,
    combined_power_rank = 3,
    members = [
      'Atanner',
      'DKPlugins',
      'Eiskalt',
      'FeTiD',
      'Kasami',
      'SBense',
      'slowmotionghost',
      'Timendainum',
      'Yoner'
    ],
    slack_channel = 'ayce-public',
    abbreviation = 'AYCE',
    alliance_power_rank = 1,
    combined_gcl_rank = 4,
    logo = 'b8f8bc9284e5a64.png',
    color = '#000000',
    spawns_rank = 3,
    members_rank = 4,
    alliance_gcl_rank = 3
  },
  PINK = {
    name = 'Be PINK or be purged!',
    rcl_rank = 19,
    combined_power_rank = 13,
    members = [ 'Cade', 'dragoonreas', 'InfiniteJoe', 'Kendalor', 'Palle' ],
    slack_channel = null,
    abbreviation = 'PINK',
    alliance_power_rank = 15,
    combined_gcl_rank = 14,
    logo = null,
    color = '#dd34eb',
    spawns_rank = 18,
    members_rank = 14,
    alliance_gcl_rank = 14
  },
  ud = {
    name = 'undefined',
    rcl_rank = 7,
    combined_power_rank = 8,
    members = [
      'a2coder',     'Azfaloth',
      'bekvon',      'Enrico',
      'FuddyDuddy',  'Garland',
      'Hosmagix',    'kmc2012',
      'kshepard',    'Laturb',
      'Mordox',      'Nisou',
      'p0x',         'pseudonormal',
      'Raddafiskie', 'Revrick',
      'ScottyC',     'squisher',
      'TranceCake',  'vrs',
      'zaspect'
    ],
    slack_channel = 'ud',
    abbreviation = 'ud',
    alliance_power_rank = 7,
    combined_gcl_rank = 8,
    logo = 'bf0de841d0278ba.jpg',
    color = '#2AABFF',
    spawns_rank = 7,
    members_rank = 10,
    alliance_gcl_rank = 8
  },
  TW = {
    name = 'TeamWork',
    rcl_rank = 9,
    combined_power_rank = 11,
    members = [
      'Aethercyn', 'Arivul',
      'Balthael',  'BlueskyFR',
      'Chris1',    'Enudoran',
      'GitLike',   'Harlem',
      'HerrKai'
    ],
    slack_channel = 'teamwork-public',
    abbreviation = 'TW',
    alliance_power_rank = 12,
    combined_gcl_rank = 12,
    logo = 'cb6869d8e781aca.png',
    color = '#000000',
    spawns_rank = 9,
    members_rank = 8,
    alliance_gcl_rank = 16
  },
  Overlords = {
    name = 'Spawn More Overlords',
    rcl_rank = 4,
    combined_power_rank = 5,
    members = [
      'Arcath',       'ballisto',       'BarryOSeven',
      'Blaugaard',    'BrinkDaDrink',   'Ceggindeggar',
      'Conventia',    'deft-code',      'Donat',
      'efyx',         'GimmeCookies',   'HailHydra',
      'herghost',     'KageJ',          'Kamots',
      'kirk',         'KOR_Solidarity', 'Mitsuyoshi',
      'Nyoom',        'Pav234',         'Phisec',
      'Picoplankton', 'PostCrafter',    'redTie',
      'Rising',       'Shibdib',        'Smokeman',
      'SpaceRedleg',  'Telemac',        'Troedfach',
      'Tyac',         'Vipo',           'wages123',
      'Zenga'
    ],
    slack_channel = 'overlords',
    abbreviation = 'Overlords',
    alliance_power_rank = 5,
    combined_gcl_rank = 2,
    logo = '505c8c3c7f78c26.png',
    color = '#000000',
    spawns_rank = 4,
    members_rank = 3,
    alliance_gcl_rank = 4
  },
  CoPS = {
    name = 'Greater North-Eastern Co-Prosperity Sphere',
    rcl_rank = 2,
    combined_power_rank = 2,
    members = [
      'ART999',    'Aundine',
      'ben2',      'demawi',
      'DomNomNom', 'Fritee',
      'iceburg',   'ICED_COFFEE',
      'Jibol',     'Jumpp',
      'Kotarou',   'Montblanc',
      'mute',      'o4kapuk',
      'Robalian',  'shadow_bird',
      'szumi',     'TheCreepz',
      'ThyReaper', 'TiffanyTrump',
      'Xist',      'Xolym'
    ],
    slack_channel = 'cops_public',
    abbreviation = 'CoPS',
    alliance_power_rank = 2,
    combined_gcl_rank = 3,
    logo = 'df3da6aad097e1f.jpg',
    color = '#000000',
    spawns_rank = 2,
    members_rank = 5,
    alliance_gcl_rank = 2
  },
  SRO = {
    name = 'SemperRexOffica',
    rcl_rank = 14,
    combined_power_rank = 18,
    members = [ 'Morphaana', 'NihilRex', 'SemperRabbit', 'weekOff' ],
    slack_channel = 'sro_public',
    abbreviation = 'SRO',
    alliance_power_rank = 18,
    combined_gcl_rank = 15,
    logo = 'add467f4707298c.png',
    color = '#000000',
    spawns_rank = 14,
    members_rank = 18,
    alliance_gcl_rank = 13
  },
  SUN = {
    name = 'Screeps United Nations',
    rcl_rank = 6,
    combined_power_rank = 4,
    members = [
      'andrwmorph',      'Ashburnie',
      'Atlan',           'Baezon',
      'BlackLotus',      'bldinator',
      'Calame',          'ChaosDMG',
      'deadlypineapple', 'DoofenShmirtz',
      'Finndibaen',      'Gink',
      'Hachima',         'joshua00214',
      'Klapaucius',      'Lomewilwarin',
      'Maxion',          'neomatrix',
      'Nephanae',        'Pundemonium',
      'roncli',          'seancl',
      'Sheeo',           'Tanjera',
      'Voronoi',         'Xoc',
      'zGeneral'
    ],
    slack_channel = 'sun',
    abbreviation = 'SUN',
    alliance_power_rank = 4,
    combined_gcl_rank = 6,
    logo = 'b68cbde9a812760.png',
    color = '#000000',
    spawns_rank = 5,
    members_rank = 7,
    alliance_gcl_rank = 5
  },
  TMBa = {
    name = 'Too Much Bacon',
    rcl_rank = 20,
    combined_power_rank = 19,
    members = [ 'Estecka', 'MarvinTMB', 'severedx', 'tablekorner', 'Tirix' ],
    slack_channel = 'tmba-private-chat',
    abbreviation = 'TMBa',
    alliance_power_rank = 19,
    combined_gcl_rank = 21,
    logo = '6456cc99a579c74.png',
    color = '#000000',
    spawns_rank = 21,
    members_rank = 20,
    alliance_gcl_rank = 21
  },
  int_max = {
    name = 'INTEGER_MAX',
    rcl_rank = 17,
    combined_power_rank = 17,
    members = [
      'apemanzilla',  'Dangermouse',
      'DewJunkie',    'Eugene95',
      'Hiryus',       'Jedislight',
      'Kalohi',       'Leonyx',
      'Lisp',         'Lur',
      'Meridion',     'RediJedi',
      'Rexalicious',  'Rubra',
      'Selesthiel',   'ShadyKutz',
      'starwar15432', 'theKraken',
      'utiuti',       'Winter_Owl',
      'ZenTetra'
    ],
    slack_channel = 'int_max_general',
    abbreviation = 'int_max',
    alliance_power_rank = 17,
    combined_gcl_rank = 10,
    logo = '984738d61ab9bf8.png',
    color = '#000000',
    spawns_rank = 17,
    members_rank = 12,
    alliance_gcl_rank = 9
  }
}